# Generated by Django 4.2.1 on 2023-06-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="hits",
            field=models.IntegerField(default=0),
        ),
    ]
