# Generated by Django 4.2.1 on 2023-06-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_article_hits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="hits",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
