# Generated by Django 4.2.1 on 2023-06-15 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_hitscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="hitscount",
            name="expire_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
